# -----------------------------------------------------------------------------
# <copyright file="appveyor.yml" company="MTCS">
# Copyright (c) MTCS 2024.
# MTCS is a trading name of Meridian Technology Consultancy Services Ltd.
# Meridian Technology Consultancy Services Ltd is registered in England and
# Wales. Company number: 11184022.
# </copyright>
# -----------------------------------------------------------------------------

# Configuration
configuration: release

# Only master branch
branches:
  only:
  - master
  
# Linux
image: Ubuntu

# Build script
build_script:
- cmd: |
    dotnet test src\Meridian.MeaningfulToString.Tests\Meridian.MeaningfulToString.Tests.csproj
    dotnet pack src\Meridian.MeaningfulToString\Meridian.MeaningfulToString.csproj --output %APPVEYOR_BUILD_FOLDER%

# Artifact Config
artifacts:
  - path: "*.nupkg"
    name: Meridian.MeaningfulToString NuGet Package